### ISSUE TITLE
Crashing in 1.19.2 fabric

### ISSUE THREAD

**Issue by Thelegendking** [DeaninCraft/Xp-From-Crops#6]
I have only 4 mods which are Sodium, lithium, Starlight and this mod, when starting the game I get this crash but removing this mod solves the issue of crash.
![Report](https://user-images.githubusercontent.com/89863459/205643073-aef2840c-2181-4f4f-9a47-1f1bb27be865.png)

**Comment by anoomolu** [comment]
It works fine for me, you probably need to install fabric api.

**Comment by Thelegendking** [comment]
Yep that was it, I'll delete this thanks

**Comment by Thelegendking** [comment]
Oh and please add fabric api to "required dependencies" that'll help alot of people who're having this problem.
